### ISSUE TITLE
CreateAdminService

### ISSUE THREAD

**Issue by mib32** [RailsApps/rails_apps_composer#332]
Not really an issue, i'm just really interested what kind of pattern it is? Why to create whole file app/services/create_admin_service.rb for just seeding the admin user? Why not to move it to seeds.rb? Because it not seems to be reusable.

**Comment by DanielKehoe** [comment]
Separation of concerns. In this case, it makes it easier to maintain Rails Composer because different starter apps require different additions to the *seeds.rb* file. Another approach is to add all the required code to the *seeds.rb* file but that would create a messy complex recipe in the rails_apps_composer gem.

**Comment by mib32** [comment]
Thanks @DanielKehoe
